### ISSUE TITLE
兄台想必你是写PHP的吧？

### ISSUE THREAD

**Issue by klausgao** [fritx/wxbot#10]
变量名都带$，另外语句不带;结尾，改了我很久啊

**Comment by klausgao** [comment]
没有恶意哦，码农间的玩笑ㄟ(⊙ω⊙ㄟ)哈

**Comment by fritx** [comment]
不带分号是npm的官方规范哦，不过有些规则需要注意。
小弟这篇装逼博文，不怕取笑：http://blog.fritx.me/?2015/01/why-no-semicolon

**Comment by klausgao** [comment]
@fritx 不过确实也是看各人习惯的啦，我是习惯了分号，感觉思路清晰些，所以才改了很久。
