### ISSUE TITLE
您好，我安装不上

### ISSUE THREAD

**Issue by changhaonan** [fritx/wxbot#20]
sh: 1: node: not found
npm WARN wxbot@0.1.0 No license field.
npm ERR! Linux 4.9.18-1-lts
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/changhaonan/Harvey-lab/Reminder/wxbot/npm-debug.log

**Comment by fritx** [comment]
@touching-foots-huskie 你好，

根据错误`sh: 1: node: not found`查看几个类似的issue以及stackoverflow答案：
- https://github.com/yakyak/yakyak/issues/200
- https://github.com/linnovate/mean/issues/731
- http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

可能是某些操作系统，通过某些途径安装nodejs时，提供的命令不是`node`而是`nodejs`，解决方法：
1. stackoverflow中提到的hack：进入`which nodejs`返回的相关目录，然后`ln -s nodejs node`。
2. 或者，推荐使用[nvm](http://nvm.sh/)进行node版本管理/切换，它会提供`node`命令。
