### ISSUE TITLE
运行原生场景下的微信

### ISSUE THREAD

**Issue by lin-123** [fritx/wxbot#24]
怎么运行安卓或者iOS环境的下微信。
因为网页版微信有一些消息收不到，如红包， 群邀请

**Comment by freedomlang** [comment]
这些问题在这里问不太合适吧？

**Comment by fritx** [comment]
web微信确实功能少，运行原生的工具我也不了解哈，如果有可以整理一些awesome列表

**Comment by lin-123** [comment]
发现了一个运行web版且功能比较齐全的工具。 可以发送名片，群邀请，同意加好友等功能 
[wechaty](https://github.com/Chatie/wechaty)
